### ISSUE TITLE
Cupboard capacity is no longer updated

### ISSUE THREAD

**Issue by gkalomiros** [GruffCassquatch/ContainerTweaks#1]
I can save cupboard capacity in the settings, but the mod doesn't update the actual capacity of cupboards anymore. Root cause appears to be that this condition was removed from `Patches.cs`
```C#
else if (__instance.m_DisplayName == "Cupboard") __instance.m_CapacityKG = Settings.settings.cupboardCapacity;
```

**Comment by GruffCassquatch** [comment]
Which cupboard is not updating? Can you please let me know the exact location. The game has several items with the same display name, so it's easy to miss one.

**Comment by gkalomiros** [comment]
The container in question is "Mystery Lake" > "Camp Office" > upstairs next to the bunk beds on the right and against the same wall as the welcome sign.

**Comment by GruffCassquatch** [comment]
Thanks, I have added the missing cupboard and a new version is up

**Comment by gkalomiros** [comment]
Verified on my instance. Thanks!

**Comment by GruffCassquatch** [comment]
Thanks for letting me know!
